server:
  port: 31400
spring:
  application:
    name: service-manage-media
  data:
    mongodb:
      uri:  mongodb://root:123@localhost:27017
      database: xc_media
lightspace:
  upload-location: ./develop/video/
  mq:
    routingkey-media-video: routingkey_media_video
eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: ${EUREKA_SERVER:http://localhost:50101/eureka/}
  instance:
    prefer-ip-address:  true
    ip-address: ${IP_ADDRESS:127.0.0.1}
    instance-id: ${spring.application.name}:${server.port}
ribbon:
  MaxAutoRetries: 2
  MaxAutoRetriesNextServer: 3
  OkToRetryOnAllOperations: false
  ConnectTimeout: 5000
  ReadTimeout: 6000
