server:
  port: 22100
spring:
  application:
    name: service-base-filesystem
  data:
    mongodb:
      database: xc_fs
      uri: mongodb://root:123@127.0.0.1:27017
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 0
      location:
      max-file-size: 1MB
      max-request-size: 30MB
lightspace:
  fastdfs:
    connect_timeout_in_seconds: 5
    network_timeout_in_seconds: 30
    charset: UTF-8
    tracker_servers: 192.168.101.65:22122